name: Build and Push Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah

      - name: Authenticate with Artifactory/Docker Hub
        run: |
          mkdir -p $HOME/.docker
          echo "${{ secrets.DOCKERHUB_USERNAME }}"
          echo "{\"auths\":{\"mahlomojats/1000eyes\": {\"username\": \"$DOCKERHUB_USERNAME\", \"password\": \"$DOCKERHUB_TOKEN\"}}}" > $HOME/.docker/config.json
          buildah login --authfile $HOME/.docker/config.json docker.io

        env: 
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}   

      # - name: Build with Buildah
      #   run:
      #     buildah bud -t  docker.io/mahlomojats/1000eyes:test .
          
      # - name: Buildah list images
      #   run:
      #     buildah images
          
      # - name: Push with Buildah
      #   run:
      #     buildah push --log-level=debug docker.io/mahlomojats/1000eyes:test
