name: Build and Push Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2  
    - name: Verify Docker Status
      run: |
        systemctl status docker  
