name: Kaniko Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Kaniko
      - name: Set up Kaniko
        run: |
          wget https://github.com/GoogleContainerTools/kaniko/archive/refs/tags/v1.19.2.tar.gz -q
          mkdir -p $HOME/kaniko/bin
          tar -xvf v1.19.2.tar.gz -C $HOME/kaniko/bin

      # Build and push Docker image using Kaniko
      - name: Build and push Docker image
        run: |
          ls -la $HOME/kaniko/bin

        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
